from __future__ import annotations

DASHBOARD_HTML_V50 = r"""
<!doctype html><html lang="vi"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Strategy Research V5.0</title>
<style>
:root{--bg:#08101d;--p:#101b2c;--p2:#142238;--line:#263955;--txt:#eaf2ff;--mut:#8fa3bd;--g:#39d98a;--r:#ff6b7a;--w:#f7c65c}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--txt);font:14px Segoe UI,Arial}.app{display:grid;grid-template-columns:215px 1fr;min-height:100vh}.side{background:#0b1524;border-right:1px solid var(--line);padding:18px}.brand{font-size:18px;font-weight:800}.sub,.mut{color:var(--mut);font-size:12px}.nav{margin-top:18px}.nav button,.btn{border:1px solid transparent;background:transparent;color:var(--mut);padding:9px;border-radius:8px;cursor:pointer}.nav button{width:100%;text-align:left}.nav button.active,.nav button:hover,.btn{background:var(--p2);color:var(--txt);border-color:var(--line)}main{padding:22px;min-width:0}.top{display:flex;justify-content:space-between;align-items:center}.section{display:none}.section.active{display:block}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.card{background:var(--p);border:1px solid var(--line);border-radius:11px;padding:13px;margin:9px 0}.k{font-size:11px;color:var(--mut);text-transform:uppercase}.v{font-size:20px;font-weight:800;margin-top:4px}.good{color:var(--g)}.bad{color:var(--r)}.warn{color:var(--w)}table{width:100%;border-collapse:collapse;background:var(--p)}th,td{padding:8px;border-bottom:1px solid var(--line);font-size:12px;text-align:left;vertical-align:top}th{background:#132035}.scroll{overflow:auto;max-height:65vh}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.field label{display:block;color:var(--mut);font-size:11px;margin-bottom:3px}.field input,.field select{width:100%;background:#0c1626;color:var(--txt);border:1px solid var(--line);padding:7px;border-radius:6px}.badge{border:1px solid var(--line);border-radius:999px;padding:2px 6px;font-size:10px}.evidence a{color:#8fc1ff}.modal{display:none;position:fixed;inset:0;background:#000b;z-index:10;padding:3vh 3vw;overflow:auto}.modal.open{display:block}.box{max-width:1200px;margin:auto;background:#0d1828;border:1px solid var(--line);border-radius:12px;padding:15px}canvas{width:100%;height:420px;background:#091321;border:1px solid var(--line)}pre{white-space:pre-wrap;background:#091321;padding:10px;border:1px solid var(--line);border-radius:8px}.gates{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.gate{background:#0c1727;border:1px solid var(--line);padding:7px;border-radius:7px}@media(max-width:900px){.app{grid-template-columns:1fr}.side{border-right:0}.nav{display:flex;overflow:auto}.nav button{min-width:max-content}.grid,.form,.gates{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid,.form,.gates{grid-template-columns:1fr}}
</style></head><body>
<div class="app"><aside class="side"><div class="brand">Strategy Research</div><div class="sub">V5.0 Adaptive Paper Platform</div>
<div class="nav"><button class="active" data-tab="overview">Overview</button><button data-tab="cases">Strategy Control</button><button data-tab="trades">Trade Journal</button><button data-tab="spot">Spot Narratives</button><button data-tab="evaluation">Evaluation</button><button data-tab="system">System</button></div></aside>
<main><div class="top"><div><h2 id="title">Overview</h2><div id="updated" class="mut"></div></div><div><button class="btn" onclick="post('/scan/run')">Scan</button> <button class="btn" onclick="post('/news/run')">News</button> <button class="btn" onclick="post('/spot/research/run')">Spot</button> <button class="btn" onclick="loadAll()">Refresh</button></div></div>
<section id="overview" class="section active"><div id="cards" class="grid"></div><h3>Cases</h3><div id="overviewCases" class="scroll"></div><h3>News Guardian</h3><div id="guardian" class="card"></div></section>
<section id="cases" class="section"><div class="card"><h3 id="formTitle">Create case without editing code</h3><div class="form">
<div class="field"><label>Name</label><input id="f_name"></div><div class="field"><label>Direction</label><select id="f_direction"><option>BASE</option><option>REVERSE</option></select></div><div class="field"><label>R:R</label><input id="f_rr" type="number" step=".1" value="1"></div><div class="field"><label>Exit mode</label><select id="f_exit"><option>FIXED_RR</option><option>STRUCTURE_TARGET</option><option>ADAPTIVE</option></select></div>
<div class="field"><label>Score min</label><input id="f_smin" type="number" value="75"></div><div class="field"><label>Score max</label><input id="f_smax" type="number" value="100"></div><div class="field"><label>BTC regimes</label><input id="f_reg" value="BULLISH,BEARISH,NEUTRAL"></div><div class="field"><label>Side</label><select id="f_side"><option>BOTH</option><option>LONG</option><option>SHORT</option></select></div>
<div class="field"><label>Min volume</label><input id="f_vol" type="number" step=".05" value=".85"></div><div class="field"><label>Min OI change %</label><input id="f_oi" type="number" step=".1"></div><div class="field"><label>Funding min</label><input id="f_fmin" type="number" step=".0001"></div><div class="field"><label>Funding max</label><input id="f_fmax" type="number" step=".0001"></div><div class="field"><label>ATR min %</label><input id="f_atrmin" type="number" step=".1"></div><div class="field"><label>ATR max %</label><input id="f_atrmax" type="number" step=".1" value="7"></div><div class="field"><label>Max distance EMA20/ATR</label><input id="f_dist" type="number" step=".1"></div><div class="field"><label>Risk %</label><input id="f_risk" type="number" step=".01"></div><div class="field"><label>Max open</label><input id="f_open" type="number"></div>
<div class="field"><label>Min acceptable R</label><input id="f_minr" type="number" step=".1" value=".7"></div><div class="field"><label>Breakeven trigger R</label><input id="f_be" type="number" step=".1"></div><div class="field"><label>Trail trigger R</label><input id="f_trail" type="number" step=".1"></div><div class="field"><label>Trail lock R</label><input id="f_lock" type="number" step=".1" value=".25"></div>
</div><p><button class="btn" onclick="saveCase()">Save</button> <button class="btn" onclick="clearForm()">Clear</button></p></div><div id="caseTable" class="scroll"></div></section>
<section id="trades" class="section"><p class="mut">Bấm View để xem chart, Entry/Exit, thesis lúc vào và attribution sau khi đóng.</p><div id="tradeTable" class="scroll"></div></section>
<section id="spot" class="section"><p class="mut">News-first: narrative → evidence → coin. Không tự ra lệnh mua Spot.</p><div id="narratives"></div></section>
<section id="evaluation" class="section"><p class="mut">Không chọn winner chỉ bằng win rate: dùng expectancy, PF, DD, stability, attribution và Monte Carlo.</p><div id="evals"></div></section>
<section id="system" class="section"><pre id="sys"></pre></section></main></div>
<div id="modal" class="modal"><div class="box"><div style="display:flex;justify-content:space-between"><div><h2 id="tradeTitle"></h2><div id="tradeMeta" class="mut"></div></div><button class="btn" onclick="closeTrade()">Close</button></div><p><button class="btn" onclick="reloadTrade('1m')">1m</button> <button class="btn" onclick="reloadTrade('5m')">5m</button> <button class="btn" onclick="reloadTrade('15m')">15m</button> <button class="btn" onclick="reloadTrade('1h')">1h</button></p><canvas id="chart" width="1100" height="420"></canvas><div id="tradeStats" class="grid"></div><h3>Entry thesis</h3><pre id="thesis"></pre><h3>Post-trade attribution</h3><pre id="attr"></pre></div></div>
<script>
var D={},CASES=[],EV={},currentTrade=null,editing=null;
function el(x){return document.getElementById(x)}function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}function n(x,d){return Number(x||0).toFixed(d==null?2:d)}function p(x){return '<span class="'+(Number(x)>=0?'good':'bad')+'">'+(Number(x)>=0?'+':'')+n(x,2)+'</span>'}
async function getj(u,o){var r=await fetch(u,o);if(!r.ok)throw new Error(await r.text());return r.json()}async function post(u){await getj(u,{method:'POST'});await loadAll()}
async function loadAll(){try{var a=await Promise.all([getj('/api/dashboard'),getj('/strategy/cases'),getj('/strategy/evaluation'),getj('/spot/narratives')]);D=a[0];CASES=a[1];EV=a[2];D.nr=a[3];render();el('updated').textContent='Updated '+new Date().toLocaleString()}catch(e){el('updated').textContent=e.message}}
function render(){renderOverview();renderCases();renderTrades();renderSpot();renderEval();el('sys').textContent=JSON.stringify(D.system||{},null,2)}
function renderOverview(){var sb=D.strategy_battle||{},ss=sb.strategies||[];el('cards').innerHTML='<div class="card"><div class="k">Active cases</div><div class="v">'+CASES.filter(function(x){return x.enabled&&!x.archived}).length+'</div></div><div class="card"><div class="k">Closed shown</div><div class="v">'+(D.trades||[]).length+'</div></div><div class="card"><div class="k">PnL leader</div><div class="v">'+esc(sb.leader_net_pnl||'—')+'</div></div><div class="card"><div class="k">Guardian</div><div class="v">'+esc((D.news_guardian||{}).mode||'NORMAL')+'</div></div>';var h='<table><tr><th>Case</th><th>Closed</th><th>WR</th><th>PnL</th><th>PF</th><th>Expectancy</th><th>DD</th></tr>';ss.forEach(function(s){var a=s.analytics||{};h+='<tr><td>'+esc(s.name)+'</td><td>'+(a.closed||0)+'</td><td>'+n(a.win_rate,1)+'%</td><td>'+p(a.realized_pnl)+'</td><td>'+n(a.profit_factor,2)+'</td><td>'+n(a.expectancy_r,3)+'R</td><td>'+n(a.max_drawdown_pct,2)+'%</td></tr>'});el('overviewCases').innerHTML=h+'</table>';var g=D.news_guardian||{};el('guardian').innerHTML='<b>'+esc(g.mode||'NORMAL')+'</b> • impact '+n(g.impact_score,0)+' • '+esc(g.direction||'UNCLEAR')+' '+n(g.confidence,0)+'%<br><span class="mut">'+esc(g.headline||'No active event')+'</span>'}
function renderCases(){var h='<table><tr><th>Case</th><th>Ver</th><th>Status</th><th>Dir</th><th>RR</th><th>Score</th><th>Regime</th><th>Exit</th><th>Manage</th><th>Action</th></tr>';CASES.forEach(function(x){h+='<tr><td><b>'+esc(x.short_name)+'</b> '+esc(x.name)+'</td><td>v'+x.version+'</td><td>'+(x.archived?'ARCHIVED':x.enabled?'ACTIVE':'PAUSED')+'</td><td>'+esc(x.direction_mode)+'</td><td>'+n(x.rr,1)+'</td><td>'+n(x.score_min,0)+'-'+n(x.score_max,0)+'</td><td>'+esc((x.btc_regimes||[]).join(','))+'</td><td>'+esc(x.exit_mode)+'</td><td>BE '+(x.breakeven_trigger_r==null?'—':x.breakeven_trigger_r)+' / Trail '+(x.trail_trigger_r==null?'—':x.trail_trigger_r)+'</td><td><button class="btn" onclick="editCase(\''+x.strategy_id+'\')">Edit</button> <button class="btn" onclick="cloneCase(\''+x.strategy_id+'\')">Clone</button> <button class="btn" onclick="toggleCase(\''+x.strategy_id+'\','+(!x.enabled)+')">'+(x.enabled?'Pause':'Resume')+'</button></td></tr>'});el('caseTable').innerHTML=h+'</table>'}
function vv(id){var v=el(id).value.trim();return v===''?null:v}function payload(){return {name:vv('f_name'),direction_mode:vv('f_direction'),rr:Number(vv('f_rr')),exit_mode:vv('f_exit'),score_min:Number(vv('f_smin')),score_max:Number(vv('f_smax')),btc_regimes:vv('f_reg').split(',').map(function(x){return x.trim()}),side_filter:vv('f_side'),min_volume_ratio:Number(vv('f_vol')),min_oi_change_pct:vv('f_oi')==null?null:Number(vv('f_oi')),funding_min:vv('f_fmin')==null?null:Number(vv('f_fmin')),funding_max:vv('f_fmax')==null?null:Number(vv('f_fmax')),atr_min_pct:vv('f_atrmin')==null?null:Number(vv('f_atrmin')),atr_max_pct:vv('f_atrmax')==null?null:Number(vv('f_atrmax')),max_distance_ema20_atr:vv('f_dist')==null?null:Number(vv('f_dist')),risk_pct:vv('f_risk')==null?null:Number(vv('f_risk')),max_open_trades:vv('f_open')==null?null:Number(vv('f_open')),min_acceptable_rr:Number(vv('f_minr')),breakeven_trigger_r:vv('f_be')==null?null:Number(vv('f_be')),trail_trigger_r:vv('f_trail')==null?null:Number(vv('f_trail')),trail_lock_r:Number(vv('f_lock'))}}
async function saveCase(){var u=editing?'/strategy/cases/'+editing:'/strategy/cases',m=editing?'PUT':'POST';await getj(u,{method:m,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});clearForm();await loadAll()}function clearForm(){editing=null;el('formTitle').textContent='Create case without editing code';el('f_name').value='';el('f_direction').value='BASE';el('f_rr').value='1';el('f_exit').value='FIXED_RR';el('f_smin').value='75';el('f_smax').value='100';el('f_reg').value='BULLISH,BEARISH,NEUTRAL';el('f_side').value='BOTH';el('f_vol').value='.85';el('f_oi').value='';el('f_fmin').value='';el('f_fmax').value='';el('f_atrmin').value='';el('f_atrmax').value='7';el('f_dist').value='';el('f_risk').value='';el('f_open').value='';el('f_minr').value='.7';el('f_be').value='';el('f_trail').value='';el('f_lock').value='.25'}
function editCase(id){var x=CASES.find(function(z){return z.strategy_id===id});if(!x)return;editing=id;el('formTitle').textContent='Edit '+x.name+' → v'+(x.version+1);el('f_name').value=x.name;el('f_direction').value=x.direction_mode;el('f_rr').value=x.rr;el('f_exit').value=x.exit_mode;el('f_smin').value=x.score_min;el('f_smax').value=x.score_max;el('f_reg').value=(x.btc_regimes||[]).join(',');el('f_side').value=x.side_filter;el('f_vol').value=x.min_volume_ratio==null?'':x.min_volume_ratio;el('f_oi').value=x.min_oi_change_pct==null?'':x.min_oi_change_pct;el('f_fmin').value=x.funding_min==null?'':x.funding_min;el('f_fmax').value=x.funding_max==null?'':x.funding_max;el('f_atrmin').value=x.atr_min_pct==null?'':x.atr_min_pct;el('f_atrmax').value=x.atr_max_pct==null?'':x.atr_max_pct;el('f_dist').value=x.max_distance_ema20_atr==null?'':x.max_distance_ema20_atr;el('f_risk').value=x.risk_pct==null?'':x.risk_pct;el('f_open').value=x.max_open_trades==null?'':x.max_open_trades;el('f_minr').value=x.min_acceptable_rr;el('f_be').value=x.breakeven_trigger_r==null?'':x.breakeven_trigger_r;el('f_trail').value=x.trail_trigger_r==null?'':x.trail_trigger_r;el('f_lock').value=x.trail_lock_r;document.querySelector('[data-tab=cases]').click()}
async function cloneCase(id){var name=prompt('Clone name (optional)','');await getj('/strategy/cases/'+id+'/clone',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name||null})});await loadAll()}async function toggleCase(id,en){await getj('/strategy/cases/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:en})});await loadAll()}
function renderTrades(){var ts=(D.trades||[]).slice().reverse(),h='<table><tr><th>ID</th><th>Case</th><th>Symbol</th><th>Side</th><th>Opened</th><th>Closed</th><th>Exit</th><th>PnL</th><th>R</th><th></th></tr>';ts.forEach(function(t){h+='<tr><td>#'+t.id+'</td><td>'+esc(t.strategy_name||t.strategy_id)+'</td><td><b>'+esc(t.symbol)+'</b></td><td>'+esc(t.side)+'</td><td>'+new Date(t.opened_at).toLocaleString()+'</td><td>'+new Date(t.closed_at).toLocaleString()+'</td><td>'+esc(t.exit_reason)+'</td><td>'+p(t.net_pnl)+'</td><td>'+n(t.r_multiple,2)+'R</td><td><button class="btn" onclick="openTrade('+t.id+',\'15m\')">View</button></td></tr>'});el('tradeTable').innerHTML=h+'</table>'}
async function openTrade(id,i){currentTrade=id;el('modal').classList.add('open');var x=await getj('/trades/'+id+'/detail?interval='+i);renderTrade(x)}function reloadTrade(i){if(currentTrade)openTrade(currentTrade,i)}function closeTrade(){el('modal').classList.remove('open')}
function renderTrade(x){var t=x.trade||{};el('tradeTitle').textContent='#'+t.id+' '+t.symbol+' '+t.side;el('tradeMeta').textContent=t.strategy_id+' • '+new Date(t.opened_at).toLocaleString()+' → '+new Date(t.closed_at).toLocaleString()+' • '+x.interval;el('tradeStats').innerHTML='<div class="card"><div class="k">Entry</div><div class="v">'+t.entry_price+'</div></div><div class="card"><div class="k">Exit</div><div class="v">'+t.exit_price+'</div></div><div class="card"><div class="k">SL / TP</div><div class="v" style="font-size:14px">'+t.stop_loss+' / '+t.take_profit+'</div></div><div class="card"><div class="k">PnL / R</div><div class="v">'+(Number(t.net_pnl)>=0?'+':'')+n(t.net_pnl,2)+' / '+n(t.r_multiple,2)+'R</div></div>';el('thesis').textContent=JSON.stringify(x.decision_thesis||{},null,2);el('attr').textContent=JSON.stringify(x.attribution||{},null,2);draw(x)}
function draw(x){var cv=el('chart'),q=cv.getContext('2d'),cs=x.candles||[];q.clearRect(0,0,cv.width,cv.height);if(!cs.length)return;var a=[];cs.forEach(function(c){a.push(c.high,c.low)});a.push(Number(x.markers.stop_loss),Number(x.markers.take_profit));var lo=Math.min.apply(null,a),hi=Math.max.apply(null,a),pd=(hi-lo)*.08||1;lo-=pd;hi+=pd;var L=58,R=15,T=15,B=25,W=cv.width-L-R,H=cv.height-T-B;function y(v){return T+(hi-v)/(hi-lo)*H}function xx(i){return L+(i+.5)/cs.length*W}q.strokeStyle='#1f344d';for(var k=0;k<5;k++){var yy=T+k*H/4;q.beginPath();q.moveTo(L,yy);q.lineTo(cv.width-R,yy);q.stroke();q.fillStyle='#8fa3bd';q.fillText((hi-(hi-lo)*k/4).toPrecision(7),3,yy+4)}cs.forEach(function(c,i){var up=c.close>=c.open;q.strokeStyle=up?'#39d98a':'#ff6b7a';q.fillStyle=q.strokeStyle;var z=xx(i);q.beginPath();q.moveTo(z,y(c.high));q.lineTo(z,y(c.low));q.stroke();var y1=y(Math.max(c.open,c.close)),y2=y(Math.min(c.open,c.close));q.fillRect(z-2,y1,4,Math.max(1,y2-y1))});function line(v,l,col){q.strokeStyle=col;q.setLineDash([6,4]);q.beginPath();q.moveTo(L,y(v));q.lineTo(cv.width-R,y(v));q.stroke();q.setLineDash([]);q.fillStyle=col;q.fillText(l+' '+v,L+4,y(v)-3)}line(Number(x.markers.entry.price),'ENTRY','#63a6ff');line(Number(x.markers.exit.price),'EXIT','#f7c65c');line(Number(x.markers.stop_loss),'SL','#ff6b7a');line(Number(x.markers.take_profit),'TP','#39d98a')}
function renderSpot(){var rows=(D.nr||{}).top_trends||[];el('narratives').innerHTML=rows.map(function(r){var ev=(r.evidence||[]).map(function(e){return '<li><a target="_blank" href="'+esc(e.url)+'">'+esc(e.title)+'</a><br><span class="mut">'+esc(e.source)+' • impact '+e.impact_score+' • cluster '+e.articles_in_cluster+' articles / '+e.independent_sources_in_cluster+' sources</span></li>'}).join('');var coins=(r.coins||[]).slice(0,8).map(function(c){return '<span class="badge">'+esc(c.symbol)+' '+n(c.relevance,0)+'</span> '}).join('');return '<div class="card"><div class="grid"><div><div class="k">Trend score</div><div class="v">'+n(r.trend_score,0)+'</div><span class="badge">'+esc(r.lifecycle)+'</span></div><div style="grid-column:span 3"><h3>'+esc(r.label)+'</h3><div class="mut">'+r.articles_7d+' articles • '+r.independent_sources+' sources • '+r.independent_events+' independent event clusters • '+esc(r.bias)+'</div><p>'+coins+'</p><ul class="evidence">'+ev+'</ul></div></div></div>'}).join('')}
function renderEval(){var rows=(EV||{}).cases||[];el('evals').innerHTML=rows.map(function(e){var m=e.metrics||{},r=e.readiness||{},g=r.gates||{},gs=Object.keys(g).map(function(k){var v=g[k];return '<div class="gate"><span class="'+(v.pass?'good':'bad')+'">'+(v.pass?'PASS':'WAIT')+'</span> <b>'+esc(k)+'</b><br><span class="mut">'+esc(v.value)+' • '+esc(v.target)+'</span></div>'}).join('');return '<div class="card"><div style="display:flex;justify-content:space-between"><div><b>'+esc(e.case.name)+'</b><br><span class="badge">'+esc(r.status)+' '+r.score+'/100</span></div><div class="'+(m.net_pnl>=0?'good':'bad')+'" style="font-size:20px;font-weight:800">'+(m.net_pnl>=0?'+':'')+n(m.net_pnl,2)+' USDT</div></div><div class="grid" style="margin-top:10px"><div><div class="k">Trades / WR</div><b>'+m.trades+' / '+n(m.win_rate_pct,1)+'%</b></div><div><div class="k">Expectancy</div><b>'+n(m.expectancy_r,3)+'R</b></div><div><div class="k">PF</div><b>'+(m.profit_factor==null?'—':m.profit_factor)+'</b></div><div><div class="k">Max DD</div><b>'+n(m.max_drawdown_pct,2)+'%</b></div></div><div class="gates">'+gs+'</div></div>'}).join('')}
document.querySelectorAll('.nav button').forEach(function(b){b.onclick=function(){document.querySelectorAll('.nav button').forEach(function(x){x.classList.remove('active')});document.querySelectorAll('.section').forEach(function(x){x.classList.remove('active')});b.classList.add('active');el(b.dataset.tab).classList.add('active');el('title').textContent=b.textContent}});
loadAll();setInterval(loadAll,45000);
</script></body></html>
"""
